<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Session;

class AppPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'name'=>"required",
            'app_id'=>"required",
            'secret'=>"required",
            'mch_id'=>"required",
            'api_key'=>"required",
            'template_id'=>"required",
            'cainfo'=>"required",
            'sslcert'=>"required",
            'sslkey'=>"required"
        ];
    }
    public function messages()
    {
        return [
            'name.required'=>"名称不允许为空！",
            'app_id.required'=>"AppID不允许为空！",
            'secret.required'=>"AppSecret不允许为空！",
            'mch_id.required'=>"商户号不允许为空！",
            'api_key.required'=>"ApiKey不允许为空！",
            'template_id.required'=>"通知模板ID不允许为空！",
            'cainfo.required'=>"请先上传证书！",
            'sslcert.required'=>"请先上传证书！",
            'sslkey.required'=>"请先上传证书！",
        ];
    }
    protected function formatErrors(Validator $validator)
    {
        $message = $validator->errors()->first(); // TODO: Change the autogenerated stub
//        Session::put('status',$message);
        return [$message];
    }
    public function response(array $errors)
    {
        return redirect()->back()->with('status',$errors[0]); // TODO: Change the autogenerated stub
    }
}
